### ISSUE TITLE
Dev/#8 회원가입 에러 리턴

### ISSUE THREAD

**Issue by sehwanii** [CAU-CAPSTONE-2024-TEAM2/back-end#9]
## 회원가입 에러 리턴
- [ ] Email 관련 에러
- [ ] 비밀번호 관련 에러

**Comment by coffeesigma** [comment]
사용자 정의 serializer 를 사용하면 해결될 것으로 예상됨

**Comment by coffeesigma** [comment]
email field 를 보내지 않으면 해결됨
